name: pv_analysis
channels:
  - slacgismo
  - anaconda
  - pyviz
  - plotly
  - r
  - bioconda
  - conda-forge
  - defaults
dependencies:
#########################
  - aiohttp=3.7.4
  - anyio=2.2.0
  - appdirs=1.4.4
  - appnope=0.1.2
  - argon2-cffi=20.1.0
  - async-timeout=3.0.1
  - async_generator=1.10
  - atpublic=1.0
  - attrs=20.3.0
  - babel=2.9.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bleach=3.3.0
  - bokeh=2.3.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.12.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=4.2.1
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - chart-studio=1.1.0
  - click=7.1.2
  - cloudpickle=1.6.0
  - colorama=0.4.4
  - colorcet=2.0.6
  - commonmark=0.9.1
  - configobj=5.0.6
  - cryptography=3.4.4
  - cvxpy=1.0.31
  - cvxpy-base=1.0.31
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask=2021.2.0
  - dask-core=2021.2.0
  - datashader=0.12.0
  - datashape=0.5.4
  - decorator=4.4.2
  - defusedxml=0.6.0
  - dill=0.3.3
  - diskcache=5.2.1
  - distributed=2021.2.0
  - distro=1.5.0
  - dpath=2.0.1
  - dulwich=0.20.21
  - dvc=2.0.15
  - dvc-gdrive=2.0.15
  - ecos=2.0.7.post1
  - entrypoints=0.3
  - enum34=1.1.10
  - ffmpeg=4.3.1
  - ffmpeg-python=0.2.0
  - flatten-dict=0.3.0
  - flufl.lock=3.2
  - freetype=2.10.4
  - fsspec=0.8.7
  - funcy=1.15
  - future=0.18.2
  - gettext=0.19.8.1
  - gitdb=4.0.7
  - gitdb2=4.0.2
  - gitpython=3.1.14
  - gmp=6.2.1
  - gnutls=3.6.13
  - google-api-core=1.26.2
  - google-api-python-client=2.0.2
  - google-auth=1.28.0
  - google-auth-httplib2=0.0.4
  - googleapis-common-protos=1.53.0
  - grandalf=0.6
  - hdbscan=0.8.27
  - heapdict=1.0.1
  - holoviews=1.14.1
  - httplib2=0.19.1
  - icu=68.1
  - idna=2.10
  - imagecodecs-lite=2019.12.3
  - imageio=2.9.0
  - importlib-metadata=3.7.0
  - importlib_metadata=3.7.0
  - iniconfig=1.1.1
  - ipykernel=5.3.4
  - ipython=7.21.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.18.0
  - jinja2=2.11.3
  - joblib=1.0.1
  - jpeg=9b
  - json5=0.9.5
  - jsonpath-ng=1.5.2
  - jsonschema=3.2.0
  - jupyter-packaging=0.7.12
  - jupyter_client=6.1.11
  - jupyter_core=4.7.1
  - jupyter_server=1.4.1
  - jupyterlab=3.0.9
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.3.0
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.2.0
  - kneed=0.7.0
  - lame=3.100
  - lcms2=2.11
  - libblas=3.9.0=8_openblas
  - libcblas=3.9.0=8_openblas
  - libcxx=11.0.1
  - libffi=3.3
  - libgfortran=5.0.0=9_3_0_h6c81a4c_19
  - libgfortran5=9.3.0
  - libgit2=1.1.0
  - libiconv=1.16
  - liblapack=3.9.0=8_openblas
  - libllvm10=10.0.1
  - libopenblas=0.3.12=openmp_h54245bb_1
  - libpng=1.6.37
  - libprotobuf=3.14.0
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libtiff=4.1.0
  - libuv=1.41.0
  - llvm-openmp=11.0.1
  - llvmlite=0.35.0
  - locket=0.2.0
  - lz4-c=1.9.2
  - markdown=3.3.4
  - markupsafe=1.1.1
  - matplotlib=3.3.1=0
  - matplotlib-base=3.3.1
  - mistune=0.8.4
  - more-itertools=8.7.0
  - msgpack-python=1.0.2
  - multidict=5.1.0
  - multipledispatch=0.6.0
  - multiprocess=0.70.11.1
  - nanotime=0.5.2
  - nbclassic=0.2.6
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - nettle=3.6
  - networkx=2.5
  - nodejs=12.19.0
  - notebook=6.2.0
  - numba=0.52.0
  - numpy=1.20.1
  - oauth2client=4.1.3
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1k
  - osqp=0.6.2
  - packaging=20.9
  - pandas=1.1.3
  - pandoc=2.11.4
  - pandocfilters=1.4.2
  - panel=0.10.3
  - param=1.10.1
  - parso=0.8.1
  - partd=1.1.0
  - pathlib=1.0.1
  - pathlib2=2.3.5
  - pathspec=0.8.1
  - pcre2=10.36
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.0
  - pip=21.0.1
  - plotly=4.14.3
  - pluggy=0.13.1
  - ply=3.11
  - pooch=1.3.0
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.16
  - protobuf=3.14.0
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - py=1.10.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pyct=0.4.6
  - pyct-core=0.4.6
  - pydot=1.2.4
  - pydrive2=1.8.1
  - pygit2=1.5.0
  - pygments=2.8.0
  - pygtrie=2.3.2
  - pynndescent=0.5.2
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pytest=6.2.2
  - python=3.8.8
  - python-dateutil=2.8.1
  - python_abi=3.8=1_cp38
  - pytz=2020.1
  - pyviz_comms=2.0.1
  - pywavelets=1.1.1
  - pyyaml=5.4.1
  - pyzmq=22.0.3
  - qdldl-python=0.1.5
  - readline=8.0
  - requests=2.25.1
  - retrying=1.3.3
  - rich=10.0.1
  - rsa=4.7.2
  - ruamel.yaml=0.16.12
  - ruamel.yaml.clib=0.2.2
  - scikit-image=0.18.1
  - scikit-learn=0.24.1
  - scikit-learn-extra=0.1.0b2
  - scipy=1.6.0
  - scs=2.1.2
  - seaborn=0.11.0
  - send2trash=1.5.0
  - setuptools=49.6.0
  - setuptools-scm=6.0.1
  - setuptools_scm=6.0.1
  - shortuuid=1.0.1
  - shtab=1.3.5
  - simplejson=3.17.2
  - six=1.15.0
  - smmap=3.0.5
  - sniffio=1.2.0
  - solar-data-tools=0.4.4
  - sortedcontainers=2.3.0
  - sqlite=3.34.0
  - tabulate=0.8.9
  - tbb=2020.2
  - tblib=1.6.0
  - terminado=0.9.2
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tifffile=2019.7.26.2
  - tk=8.6.10
  - toml=0.10.2
  - toolz=0.11.1
  - tornado=6.1
  - tqdm=4.60.0
  - traitlets=5.0.5
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - umap-learn=0.5.1
  - uritemplate=3.0.1
  - urllib3=1.26.3
  - voluptuous=0.12.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - x264=1!161.3030
  - xarray=0.17.0
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zc.lockfile=2.0
  - zeromq=4.3.4
  - zict=2.0.0
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - calmap==0.0.9
    - cvxcanon==0.1.2
    - fastcache==1.1.0
    - fpdf2==2.3.1
    - h5py==3.2.1
    - patsy==0.5.1
    - pvlib==0.8.1
    - rdtools==2.0.5
    - simdkalman==1.0.1
    - statsmodels==0.12.2
    - tsmoothie==1.0.1
